[package]
name = "web_socket_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.8.3", features = ["ws"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }